# Generated by Django 5.0 on 2023-12-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listmodel',
            name='Status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'In Progress'), (3, 'Completed')], default=1),
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='Due_Date',
            field=models.DateField(max_length=100),
        ),
    ]
